#server.port=8080
#
#spring.datasource.url=jdbc:sqlserver://localhost:1434;databaseName=CafeHalandDB;encrypt=true;trustServerCertificate=true;
#spring.datasource.username=sa
#spring.datasource.password=123456
#spring.jpa.show-sql=false
#spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
#
#spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.hibernate.ddl-auto=update
#
#

server:
  port: 8081
spring:
  application:
    name: "cafehalanddb1"
  datasource:
    url: jdbc:mysql://localhost:3306/cafehalanddb
    username: root
    password: 123456
  jpa:
    dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
      show-sql: true